version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    networks:
      - kafka_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    restart: always
  kafka:
    image: confluentinc/cp-kafka:7.2.2
    networks:
      - kafka_net
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
  client:
    build: ./client/
    networks:
      - kafka_net
    restart: always
  servo:
    build: ./car/utils/servo/
    networks:
      - kafka_net
    volumes:
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - /proc/device-tree/chosen:/proc/device-tree/chosen
      - /sys/devices/:/sys/devices/
      - /sys/class/gpio:/sys/class/gpio
    privileged: true
    restart: always
  dcmotor:
    build: ./car/utils/dcmotor/
    networks:
      - kafka_net
    volumes:
      - /proc/device-tree/compatible:/proc/device-tree/compatible
      - /proc/device-tree/chosen:/proc/device-tree/chosen
      - /sys/devices/:/sys/devices/
      - /sys/class/gpio:/sys/class/gpio
    privileged: true
    restart: always
  camera:
    build: ./car/utils/camera
    volumes:
      - /dev/video0:/dev/video0
      - /tmp/argus_socket:/tmp/argus_socket
    devices:
      - /dev/video0
    runtime: nvidia
    restart: always

networks:
  kafka_net: